language: python

jobs:
  include:
    - services: docker
    - os: osx
      language: shell
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe

if: tag IS present

env:
  global:
    # cpolf only works on Python >= 3.6.
    - CIBW_BUILD="cp36-* cp37-* cp38-*"
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}/test -svv"
    # - CIBW_ENVIRONMENT="DEBUG='1'"
    - TWINE_USERNAME=__token__

install:
  - pip3 install https://github.com/joerick/cibuildwheel/archive/master.zip

script:
  - cibuildwheel --output-dir wheelhouse
  # Upload wheels to PyPI on tags and source distribution from linux
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      python3 -m twine upload --skip-existing wheelhouse/*.whl
    fi
  - |
    if [[ $TRAVIS_TAG ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      python3 setup.py sdist
      python3 -m twine upload --skip-existing dist/*
    fi
